### ISSUE TITLE
Complete the region scores page template

### ISSUE THREAD

**Issue by robyngit** [OHI-Science/OHI-website#52]
The region score page template only shows a couple of visualizations at the moment, and no text.

This template requires the following elements:
- [x] The aster plot
- [x] The region ranking bar chart
- [x] The score gauge data viz (#51)
- [x] The  goal score comparison plot (#50)
- [x] The trend plot (#71)
- [x] ~~The table in the DATA tab with scores for each goal and sub-goal* (and links to goal pages)~~
- [x] The text summarizing the various values* (e.g. "The near term future state of Albania is estimated at roughly -2% compared to a global estimate of ~ 10%.")
- [x] ~~The map with the region in focus~~

\* data should be pulled in dynamically from the `content/data/scores.csv` file

**Comment by robyngit** [comment]
Note that in our meeting today, we decided not to show the "LIKELY FUTURE STATE" information. Also the "OVERALL SCORE" might only need to be shown as a metric within a circle, without the [score status bar visualization](https://github.com/OHI-Science/OHI-website/issues/51).

We would also like a visualization that shows the overall trend of the scores for the region over time, compared to other regions.

**Comment by Melsteroni** [comment]
I believe we can cut this: "The trend plot (Create the scores trend plot #71)"

Is this:  "The table in the DATA tab with scores for each goal and sub-goal* (and links to goal pages)" referring to this table in the main website:
![image](https://user-images.githubusercontent.com/5685517/129288033-2277e573-9a14-45e5-8388-065c9813e334.png)

If so: I am inclined to give this low priority.  But interested in other opinions on this.

**Comment by Melsteroni** [comment]
Let's make data tables lower priority, i.e.,

> The table in the DATA tab with scores for each goal and sub-goal* (and links to goal pages)

If we do make tables, I think they will need to be modified from oceanhealthindex.org.  This will take some thought.

**Comment by Melsteroni** [comment]
Let's make this low priority:  The map with the region in focus
